name: cupcake_orders
description: Ported cupcake ordering app to Flutter from Android Kotlin basics course.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  stacked: ^2.3.10
  flutter_svg: ^1.1.0
  collection: ^1.16.0
  url_launcher: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
